### ISSUE TITLE
Feature request: adding the possibility to customize the style of the arrows

### ISSUE THREAD

**Issue by quark67** [st--/annotate-equations#14]
For exemple, with `\annotatetwo`, we obtain a `<------->` arrow (with corners). Currently, I don't see how to pass an tikz option to the command in order to have the tip only in one side (or to have dotted or dashed or thick lines). 

I thought I could use the `annotate-equations` package to answer this question:
https://tex.stackexchange.com/questions/676227/how-to-draw-a-simple-curved-arrow-inside-of-an-equation

But currently, I cannot, because in the picture illustrating the question, the tip is only in one side, and `\annotatetwo` create an arrow with two tips, one in each side.

**Comment by st--** [comment]
I'd like `annotate-equations` to remain as simple as possible. I think we could maybe make use of pgfkeys/the way TikZ itself handles settings to make it easy to pass through options to the highlight node, the annotation node, and the arrow line... I'm not an expert at this so any help would be appreciated:)

In the meantime, the answer to the question you posted seems fairly straightforward to do it manually.

**Comment by st--** [comment]
@quark67 hi, I've just made an update that makes it easy to do all of the customizations you mention. In the end it turned out to be rather simpler than I thought! It will take a while until it's on CTAN, and probably even longer until it's in whichever TeX distribution you're using, but you can simply copy the annotate-equations.sty from this repository into your working directory until then. Please let me know if there's anything else you can't get to work with it!
