### ISSUE TITLE
compatibility with standalone (answer: yes for this package, just amsmath's `equation*` isn't)

### ISSUE THREAD

**Issue by trim1962** [st--/annotate-equations#3]
with standalone it doesn't work

```latex
\documentclass{standalone}

\usepackage{amsmath}
\usepackage{annotate-equations}

\begin{document}
	
	\renewcommand{\eqnhighlightheight}{\mathstrut}
	
	\begin{equation*}
		\eqnmark{post}{p(\theta | D)} = \frac{\eqnmark{lik}{p(D|\theta)} 
		\eqnmark{prior}{p(\theta)}} {\eqnmark{marglik}{p(D)}}
	\end{equation*}
	\annotate[yshift=2.5em]{above,right}{lik}{likelihood}
	\annotate[yshift=1em]{above,right}{prior}{prior}
	\annotate[yshift=1em]{above,left}{post}{posterior}
	\annotate[yshift=-1em]{below,right}{marglik}{marginal likelihood}
	
\end{document}
```

**Comment by st--** [comment]
Hi @trim1962 ! Thanks for your interest in the package. I've now had the chance to look at it, and the issue seems to be not with my package directly, but with the usage of the amsmath `equation*` environment, which is not compatible with the `standalone` class (see [this TeX.SE answer](https://tex.stackexchange.com/a/605209/171664)).

I can get your example to work by replacing both `\begin{equation*}` and `\end{equation*}` with `$` to turn it into a "normal" text equation.

I don't understand how `standalone` determines the box, but by default it seems to ignore the annotations and cut them off (related [TeX.SE question](https://tex.stackexchange.com/q/389190/171664)).

You can fix that by replacing the documentclass with `\documentclass[border={20pt 30pt 10pt 40pt}]{standalone}` (the four numbers are in order left, bottom, right, top margin).

Hope that helps, and please let me know if there's any further questions!
